/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmhcprms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jed
 */
public class APPOINTMENTS extends javax.swing.JFrame {

    /**
     * Creates new form APPOINTMENTS
     */
    public APPOINTMENTS() {
        initComponents();
        Connect();
        AutoID();
        showapptbl();
        showpxtbl();
        AddButton.setEnabled(false);
    }
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
     public void Connect()
{
	try {
            Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmhcprms","root","");
	} catch (ClassNotFoundException ex) {
		Logger.getLogger(DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                                 Logger.getLogger(DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
        }
}
       
       
       
       public void AutoID()
       {
        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("SELECT MAX(patientno) FROM patient_records");
            rs.next();
            rs.getString("MAX(patientno)");
            
            if(rs.getString("MAX(patientno)")== null){
                idno.setText("PX001");
            }
            else
            {
                long id=Long.parseLong(rs.getString("MAX(patientno)").substring(2,rs.getString("MAX(patientno)").length()));
                id++;
                
                idno.setText("PX"+ String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       
       public void showapptbl(){
          
            try {
                pst=conn.prepareStatement("SELECT * FROM appointments ORDER BY appno ASC");
                rs=pst.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int c;
                c = rsmd.getColumnCount();
                
                DefaultTableModel model = (DefaultTableModel)apptbl.getModel();
                model.setRowCount(0);
                
                while(rs.next() )
              {
                    Vector column  = new Vector(); 
                    
                    for(int i = 1;i<=c;i++){
                        column.add(rs.getString("appno"));
                        column.add(rs.getString("medication"));
                        column.add(rs.getString("appointment"));
                        column.add(rs.getString("staff"));
                        column.add(rs.getString("note"));
                    }
                    model.addRow(column);
                }
            } catch (SQLException ex) {
                Logger.getLogger(APPOINTMENTS.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
       public void showpxtbl(){
          
            try {
                pst=conn.prepareStatement("SELECT * FROM medical_records ORDER BY medno ASC");
                rs=pst.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int c;
                c = rsmd.getColumnCount();
                
                DefaultTableModel model = (DefaultTableModel)pxtbl.getModel();
                model.setRowCount(0);
                
                while(rs.next() )
              {
                    Vector column  = new Vector(); 
                    
                    for(int i = 1;i<=c;i++){
                         column.add(rs.getString("medno"));
                        column.add(rs.getString("medication"));
                                    }
                    model.addRow(column);
                }
            } catch (SQLException ex) {
                Logger.getLogger(APPOINTMENTS.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        apptbl = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        idno = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Tfmed = new javax.swing.JTextField();
        staff = new javax.swing.JComboBox<>();
        sched = new javax.swing.JComboBox<>();
        note = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        pxtbl = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        jButton5.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(225, 212, 187));

        jPanel1.setBackground(new java.awt.Color(83, 113, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(225, 212, 187));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 540, -1));

        jPanel4.setBackground(new java.awt.Color(203, 178, 121));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 90, 80));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MANAGE PATIENTS");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 154, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 75, 80));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PATIENT DATA");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 154, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 73, 80));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REPORTS");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 160, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prediction.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 81, 78));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRENDS AND PATTERN");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 180, 50));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1120, 140));

        jPanel5.setBackground(new java.awt.Color(225, 212, 187));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(203, 178, 121));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 80));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MANAGE PATIENTS");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 154, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appointment.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 80));

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("APPOINTMENTS");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 154, 50));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 73, 80));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("REPORTS");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 160, 50));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prediction.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 81, 78));

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TRENDS AND PATTERN");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 180, 50));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 150));

        apptbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient No", "Medication", "Appointment", "Processed by", "Noted by"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        apptbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apptblMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(apptbl);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1000, 110));

        jLabel22.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel22.setText("PATIENT ID:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 30));

        idno.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        idno.setText("Jlabel");
        jPanel5.add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel23.setText("MEDICATION");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 30));

        Tfmed.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfmedActionPerformed(evt);
            }
        });
        jPanel5.add(Tfmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 40));

        staff.setBackground(new java.awt.Color(83, 113, 136));
        staff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "STAFF 1", "STAFF 2", "STAFF 3", "STAFF 4" }));
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });
        jPanel5.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 170, 40));

        sched.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "30 DAYS", "15 DAYS", "7 DAYS" }));
        sched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedActionPerformed(evt);
            }
        });
        jPanel5.add(sched, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 160, 40));

        note.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "DOCTOR", "NURSE 1", "NURSE 2", "PSYCH 1", "PSYCH 2" }));
        jPanel5.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 170, 40));

        pxtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Patient No", "Medication"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pxtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pxtblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pxtblMouseExited(evt);
            }
        });
        pxtbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pxtblKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(pxtbl);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1000, 110));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 102));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1030, 10));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setText("SCHEDULE");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel14.setText("PROCESSED BY:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 150, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel24.setText("NOTED BY:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 130, -1));

        time.setText("TIME AND DATE");
        jPanel5.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 130, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 730));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 680, 180, -1));

        jLabel6.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 634, 540, 80));

        AddButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        AddButton.setText("ADD APPOINTMENT");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 210, 50));

        DeleteButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        DeleteButton.setText("CANCEL APPOINTMENT");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, 210, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DASHBOARD s=new DASHBOARD();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MANAGEPX s=new MANAGEPX();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        PXDATA s=new PXDATA();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        REPORTS s=new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        TRENDS s=new TRENDS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        MANAGEPX s=new MANAGEPX();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        APPOINTMENTS s=new APPOINTMENTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        REPORTS s=new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        TRENDS s=new TRENDS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void apptblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptblMouseClicked
        DefaultTableModel dl = (DefaultTableModel)apptbl.getModel();
        int SelectIndex = apptbl.getSelectedRow();

        idno.setText(dl.getValueAt(SelectIndex, 0).toString());
        Tfmed.setText(dl.getValueAt(SelectIndex, 1).toString());
        sched.setSelectedItem(dl.getValueAt(SelectIndex, 2).toString());
        staff.setSelectedItem(dl.getValueAt(SelectIndex, 3).toString());
        note.setSelectedItem(dl.getValueAt(SelectIndex, 4).toString());
        AddButton.setEnabled(false);
    }//GEN-LAST:event_apptblMouseClicked

    private void apptblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptblMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_apptblMousePressed

    private void TfmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfmedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfmedActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffActionPerformed

    private void schedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schedActionPerformed

    private void pxtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pxtblMouseClicked
        DefaultTableModel dl = (DefaultTableModel)pxtbl.getModel();
        int SelectIndex = pxtbl.getSelectedRow();

        idno.setText(dl.getValueAt(SelectIndex, 0).toString());
        Tfmed.setText(dl.getValueAt(SelectIndex, 1).toString());
       
        
        AddButton.setEnabled(true);
    }//GEN-LAST:event_pxtblMouseClicked

    private void pxtblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pxtblMouseExited

    }//GEN-LAST:event_pxtblMouseExited

    private void pxtblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pxtblKeyReleased

    }//GEN-LAST:event_pxtblKeyReleased

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String apno = idno.getText();
        String pmed = Tfmed.getText();
        String asched = (String) sched.getSelectedItem();
        String astaff = (String) staff.getSelectedItem();
        String anote = (String) note.getSelectedItem();
    

        try {
            pst = conn.prepareStatement("INSERT INTO appointments(appno, medication, appointment, staff, note) VALUES (?,?,?,?,?)");
            pst.setString(1, apno);
            pst.setString(2, pmed);
            pst.setString(3, asched);
            pst.setString(4, astaff);
            pst.setString(5, anote);
          
            

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Appointment Added");

            idno.setText("PX000");
            Tfmed.setText("");
            sched.setSelectedItem("DROP TO SELECT");
            staff.setSelectedItem("DROP TO SELECT");
            note.setSelectedItem("DROP TO SELECT");
            Tfmed.requestFocus();

            showapptbl();

        } catch (SQLException ex) {
            Logger.getLogger(APPOINTMENTS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

       
    
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String pname = Tfmed.getText();
        String vitals = (String) sched.getSelectedItem();
        String history = (String) staff.getSelectedItem();
        String med = (String) note.getSelectedItem();
        String apno = idno.getText();

        try {
            pst = conn.prepareStatement("DELETE FROM appointments WHERE appno = ?");

            pst.setString(1, apno);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Appointment cancel");

            AutoID();
            Tfmed.setText("");
            sched.setSelectedItem("DROP TO SELECT");
            staff.setSelectedItem("DROP TO SELECT");
            note.setSelectedItem("DROP TO SELECT");
            
            Tfmed.requestFocus();
            showapptbl();
            AddButton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(APPOINTMENTS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APPOINTMENTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Tfmed;
    private javax.swing.JTable apptbl;
    private javax.swing.JLabel idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> note;
    private javax.swing.JTable pxtbl;
    private javax.swing.JComboBox<String> sched;
    private javax.swing.JComboBox<String> staff;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
