/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmhcprms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jed
 */
public final class MANAGEPX extends javax.swing.JFrame {

    /**
     * Creates new form MANAGEPX
     */
    public MANAGEPX() {
        initComponents();
        Connect();
        AutoID();
        showtbl();
    }

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmhcprms", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void AutoID() {
        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("SELECT MAX(patientno) FROM patient_records");
            rs.next();
            rs.getString("MAX(patientno)");

            if (rs.getString("MAX(patientno)") == null) {
                idno.setText("PX001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(patientno)").substring(2, rs.getString("MAX(patientno)").length()));
                id++;

                idno.setText("PX" + String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showtbl() {

        try {
            pst = conn.prepareStatement("SELECT * FROM patient_records ORDER BY patientno ASC");
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c;
            c = rsmd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Vector column = new Vector();

                for (int i = 1; i <= c; i++) {
                    column.add(rs.getString("patientno"));
                    column.add(rs.getString("name"));
                    column.add(rs.getString("lastname"));
                    column.add(rs.getString("address"));
                    column.add(rs.getString("number"));
                    column.add(rs.getString("diagnosis"));
                    column.add(rs.getString("sex"));
                    column.add(rs.getString("age"));
                }
                model.addRow(column);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tfcellphone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tfage = new javax.swing.JTextField();
        Tfaddress = new javax.swing.JTextField();
        Tfname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        idno = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        Tflastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        search1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Tfdiagnosis = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        jLabel6.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(225, 212, 187));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(83, 113, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(225, 212, 187));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 624, 540, 90));

        Tfcellphone.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfcellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcellphoneActionPerformed(evt);
            }
        });
        jPanel4.add(Tfcellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 290, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel1.setText("Diagnosis");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel3.setText("PATIENT LASTNAME");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 170, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setText("AGE");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 170, 30));

        jPanel6.setBackground(new java.awt.Color(203, 178, 121));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appointment.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 80));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 75, 80));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 73, 80));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prediction.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 81, 78));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TRENDS AND PATTERN");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 180, 50));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("REPORTS");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, 50));

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PATIENT DATA");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 154, 50));

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("APPOINTMENTS");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 154, 50));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 160));

        Tfage.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfageActionPerformed(evt);
            }
        });
        jPanel4.add(Tfage, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 100, 40));

        Tfaddress.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfaddressActionPerformed(evt);
            }
        });
        jPanel4.add(Tfaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 290, 40));

        Tfname.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfnameActionPerformed(evt);
            }
        });
        jPanel4.add(Tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 40));

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient No", "Patient name", "Patient Lastname", "Patient Address", "Phone Number", "Diagnosis", "Sex", "Age"
            }
        ));
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(patientTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1010, 110));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setText("BARANGAY ADDRESS");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 30));

        idno.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        idno.setText("PX000");
        jPanel4.add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 240, 690));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setText("PATIENT ID:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setText("PATIENT NAME");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 30));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SEX", "Male", "Female", "Other" }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        jPanel4.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 100, 40));

        Tflastname.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tflastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TflastnameActionPerformed(evt);
            }
        });
        jPanel4.add(Tflastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 290, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel5.setText("CELLPHONE NUMBER");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 170, 30));

        jButton2.setBackground(new java.awt.Color(83, 113, 136));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 130, -1));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel4.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        jPanel4.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 230, 30));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 240, 70));

        Tfdiagnosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Schizophrenia", "Bipolar disorder", "Psychosis", "Personality disorder", "Obsessive–compulsive disorder", "Eating disorder", "Anxiety disorder", "Mood disorder", "Post-traumatic stress disorder." }));
        jPanel4.add(Tfdiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 690));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jPanel2.setBackground(new java.awt.Color(83, 113, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(225, 212, 187));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 180, -1));

        EditButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        EditButton.setText("UPDATE PATIENT");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel2.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 180, 50));

        AddButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        AddButton.setText("ADD PATIENT");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 180, 50));

        DeleteButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE PATIENT");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 180, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1260, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TfcellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcellphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcellphoneActionPerformed

    private void TfageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfageActionPerformed

    private void TfaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfaddressActionPerformed

    private void TfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfnameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        APPOINTMENTS s = new APPOINTMENTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        PXDATA s = new PXDATA();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        REPORTS s = new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        TRENDS s = new TRENDS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String pname = Tfname.getText();
        String plastname = Tfage.getText();
        String paddress = Tfaddress.getText();
        String pphone = Tfcellphone.getText();
        String pdiagnosis = (String) Tfdiagnosis.getSelectedItem();

        String psex = (String) sex.getSelectedItem();
        String page = Tfage.getText();
        String pno = idno.getText();

        try {
            pst = conn.prepareStatement("DELETE FROM patient_records WHERE patientno = ?");

            pst.setString(1, pno);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Patient Deleted");

            AutoID();
            Tfname.setText("");
            Tflastname.setText("");
            Tfaddress.setText("");
            Tfcellphone.setText("");
            Tfdiagnosis.setSelectedItem(null);
            sex.setSelectedItem("Select Sex");
            Tfage.setText("");
            Tfname.requestFocus();
            showtbl();
            AddButton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String pno = idno.getText();
        String pname = Tfname.getText();
        String plastname = Tflastname.getText();
        String paddress = Tfaddress.getText();
        String pphone = Tfcellphone.getText();
        String pdiagnosis = (String) Tfdiagnosis.getSelectedItem();

        String psex = (String) sex.getSelectedItem();
        String page = Tfage.getText();

        try {
            pst = conn.prepareStatement("INSERT INTO patient_records(patientno,name,lastname,address,number,diagnosis,sex,age) VALUES (?,?,?,?,?,?,?,?)");
            pst.setString(1, pno);
            pst.setString(2, pname);
            pst.setString(3, plastname);
            pst.setString(4, paddress);
            pst.setString(5, pphone);
            pst.setString(6, pdiagnosis);
            pst.setString(7, psex);
            pst.setString(8, page);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Patient added");

            AutoID();
            Tfname.setText("");
            Tflastname.setText("");
            Tfaddress.setText("");
            Tfcellphone.setText("");
            Tfdiagnosis.setSelectedItem(null);
            sex.setSelectedItem("SELECT SEX");
            Tfage.setText("");
            Tfname.requestFocus();

            showtbl();

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed

        String pname = Tfname.getText();
        String plastname = Tflastname.getText();
        String paddress = Tfaddress.getText();
        String pphone = Tfcellphone.getText();
        String pdiagnosis = (String) Tfdiagnosis.getSelectedItem();
        String psex = (String) sex.getSelectedItem();
        String page = Tfage.getText();
        String pno = idno.getText();

        try {
            pst = conn.prepareStatement("UPDATE patient_records SET name = ?, lastname = ? , address = ? , number = ? , diagnosis = ?, sex = ?, age = ? WHERE patientno = ?");

            pst.setString(1, pname);
            pst.setString(2, plastname);
            pst.setString(3, paddress);
            pst.setString(4, pphone);
            pst.setString(5, pdiagnosis);
            pst.setString(7, psex);
            pst.setString(8, page);
            pst.setString(6, pno);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Patient Updated");

            AutoID();
            Tfname.setText("");
            Tflastname.setText("");
            Tfaddress.setText("");
            Tfcellphone.setText("");
            Tfdiagnosis.setSelectedItem(null);

            sex.setSelectedItem("SELECT SEX");
            Tfage.setText("");
            Tfname.requestFocus();
            showtbl();
            AddButton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DASHBOARD s = new DASHBOARD();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
        DefaultTableModel dl = (DefaultTableModel) patientTable.getModel();
        int SelectIndex = patientTable.getSelectedRow();

        idno.setText(dl.getValueAt(SelectIndex, 0).toString());
        Tfname.setText(dl.getValueAt(SelectIndex, 1).toString());
        Tflastname.setText(dl.getValueAt(SelectIndex, 2).toString());
        Tfaddress.setText(dl.getValueAt(SelectIndex, 3).toString());
        Tfcellphone.setText(dl.getValueAt(SelectIndex, 4).toString());
        Tfdiagnosis.setSelectedItem(dl.getValueAt(SelectIndex, 5).toString());
        sex.setSelectedItem(dl.getValueAt(SelectIndex, 6).toString());
        Tfage.setText(dl.getValueAt(SelectIndex, 7).toString());
        AddButton.setEnabled(false);
    }//GEN-LAST:event_patientTableMouseClicked

    private void TflastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TflastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TflastnameActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tfname.setText("");
        Tflastname.setText("");
        Tfaddress.setText("");
        Tfcellphone.setText("");
        Tfdiagnosis.setSelectedItem(null);
        sex.setSelectedItem("Select Sex");
        Tfage.setText("");
        AddButton.setEnabled(true);
        Tfname.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        DefaultTableModel tblmodel = (DefaultTableModel) patientTable.getModel();
        String show = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tblmodel);
        patientTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(show));
    }//GEN-LAST:event_searchKeyReleased

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        DefaultTableModel tblmodel = (DefaultTableModel) patientTable.getModel();
        String show = search.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tblmodel);
        patientTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(show));
    }//GEN-LAST:event_search1KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = Ge.getConnection();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGEPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGEPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGEPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGEPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEPX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField Tfaddress;
    private javax.swing.JTextField Tfage;
    private javax.swing.JTextField Tfcellphone;
    private javax.swing.JComboBox<String> Tfdiagnosis;
    private javax.swing.JTextField Tflastname;
    private javax.swing.JTextField Tfname;
    private javax.swing.JLabel idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JComboBox<String> sex;
    // End of variables declaration//GEN-END:variables
}
