/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmhcprms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jed
 */
public final class PXDATA extends javax.swing.JFrame {

    /**
     * Creates new form PXDATA
     */
    public PXDATA() {
        initComponents();
        Connect();
        AutoID();
        showtpatientbl();
        showmedtbl();
    }
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void showtpatientbl(){
          
            try {
                pst=conn.prepareStatement("SELECT * FROM patient_records ORDER BY patientno ASC");
                rs=pst.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int c;
                c = rsmd.getColumnCount();
                
                DefaultTableModel model = (DefaultTableModel)patientTable.getModel();
                model.setRowCount(0);
                
                while(rs.next() )
              {
                    Vector column  = new Vector(); 
                    
                    for(int i = 1;i<=c;i++){
                        column.add(rs.getString("patientno"));
                        column.add(rs.getString("name"));
                    }
                    model.addRow(column);
                }
            } catch (SQLException ex) {
                Logger.getLogger(PXDATA.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    
      public void showmedtbl(){
          
            try {
                pst=conn.prepareStatement("SELECT * FROM medical_records ORDER BY medno ASC");
                rs=pst.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int c;
                c = rsmd.getColumnCount();
                
                DefaultTableModel model = (DefaultTableModel)MedTable.getModel();
                model.setRowCount(0);
                
                while(rs.next() )
              {
                    Vector column  = new Vector(); 
                    
                    for(int i = 1;i<=c;i++){
                        column.add(rs.getString("medno"));
                        column.add(rs.getString("medname"));
                        column.add(rs.getString("vitals"));
                        column.add(rs.getString("history"));
                        column.add(rs.getString("medication"));
                        column.add(rs.getString("treatment"));
                    }
                    model.addRow(column);
                }
            } catch (SQLException ex) {
                Logger.getLogger(PXDATA.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    
    public void AutoID()
       {
        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("SELECT MAX(patientno) FROM patient_records");
            rs.next();
            rs.getString("MAX(patientno)");
            
            if(rs.getString("MAX(patientno)")== null){
                idno.setText("PX001");
            }
            else
            {
                long id=Long.parseLong(rs.getString("MAX(patientno)").substring(2,rs.getString("MAX(patientno)").length()));
                id++;
                
                idno.setText("PX"+ String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PXDATA.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    
   
    
    public void Connect()
{
	try {
            Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pmhcprms","root","");
	} catch (ClassNotFoundException ex) {
                               Logger.getLogger(PXDATA.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                               Logger.getLogger(PXDATA.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MedTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        idno = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tfname = new javax.swing.JTextField();
        Jhistory = new javax.swing.JComboBox<>();
        Jvitals = new javax.swing.JComboBox<>();
        Jmed = new javax.swing.JComboBox<>();
        Jtment = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MANAGE PATIENTS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appointment.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("APPOINTMENTS");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PATIENT DATA");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REPORTS");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prediction.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRENDS AND PATTERN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(225, 212, 187));

        jPanel1.setBackground(new java.awt.Color(83, 113, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(225, 212, 187));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 634, 540, 80));

        jPanel2.setBackground(new java.awt.Color(203, 178, 121));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 80));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MANAGE PATIENTS");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 154, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appointment.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 80));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("APPOINTMENTS");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 154, 50));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 73, 80));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("REPORTS");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 160, 50));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prediction.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 81, 78));

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TRENDS AND PATTERN");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 180, 50));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 150));

        MedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient No", "Patient name", "Vital Records", "Medical History", "Medication", "Treatment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MedTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(MedTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1000, 110));

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel16.setText("PATIENT ID:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 30));

        idno.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        idno.setText("Jlabel");
        jPanel4.add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel17.setText("PATIENT NAME");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 30));

        Tfname.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfnameActionPerformed(evt);
            }
        });
        jPanel4.add(Tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 40));

        Jhistory.setBackground(new java.awt.Color(83, 113, 136));
        Jhistory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "TRAUMA", "ABUSE", "ADDICTION (DRUGS)", "GENETICS", "ACCIDENT" }));
        Jhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhistoryActionPerformed(evt);
            }
        });
        jPanel4.add(Jhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 170, 40));

        Jvitals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "BELOW NORMAL", "NORMAL", "ABOVE NORMAL" }));
        Jvitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JvitalsActionPerformed(evt);
            }
        });
        jPanel4.add(Jvitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 160, 40));

        Jmed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "RESPERIDON", "BIPERIDEN", "ANTI-PSYCHOTIC (INJECTION)", "THERAPY" }));
        jPanel4.add(Jmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 170, 40));

        Jtment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DROP TO SELECT", "MEDICATION", "REHABILITATION", "COUNSELING" }));
        jPanel4.add(Jtment, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 170, 40));

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Patient No", "Patient name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientTableMouseExited(evt);
            }
        });
        patientTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patientTableKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(patientTable);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1000, 110));

        jSeparator1.setBackground(new java.awt.Color(255, 153, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 102));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1030, 10));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 180, -1));

        AddButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        AddButton.setText("ADD INFO");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 150, 170, 50));

        EditButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        EditButton.setText("UPDATE INFO");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, 180, 50));

        DeleteButton.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE INFO");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 180, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DASHBOARD s=new DASHBOARD();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MANAGEPX s=new MANAGEPX();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        APPOINTMENTS s=new APPOINTMENTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        PXDATA s=new PXDATA();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        REPORTS s=new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        TRENDS s=new TRENDS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        MANAGEPX s=new MANAGEPX();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        APPOINTMENTS s=new APPOINTMENTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        REPORTS s=new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        TRENDS s=new TRENDS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String pno = idno.getText();
        String pname = Tfname.getText();
        String vitals = (String) Jvitals.getSelectedItem();
        String history = (String) Jhistory.getSelectedItem();
        String med = (String) Jmed.getSelectedItem();
        String tment = (String) Jtment.getSelectedItem();

        try {
            pst = conn.prepareStatement("INSERT INTO medical_records(medno, medname, vitals, history, medication, treatment) VALUES (?,?,?,?,?,?)");
            pst.setString(1, pno);
            pst.setString(2, pname);
            pst.setString(3, vitals);
            pst.setString(4, history);
            pst.setString(5, med);
            pst.setString(6, tment);
        
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Info Added");

            idno.setText("PX000");
            Tfname.setText("");
            Jvitals.setSelectedItem("DROP TO SELECT");
            Jhistory.setSelectedItem("DROP TO SELECT");
            Jmed.setSelectedItem("DROP TO SELECT");
            Jtment.setSelectedItem("DROP TO SELECT");
            Tfname.requestFocus();

            showmedtbl();

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed

        String pname = Tfname.getText();
        String vitals = (String) Jvitals.getSelectedItem();
        String history = (String) Jhistory.getSelectedItem();
        String med = (String) Jmed.getSelectedItem();
        String tment = (String) Jtment.getSelectedItem();
        String pno = idno.getText();

        try {
            pst = conn.prepareStatement("UPDATE medical_records SET medname = ?, vitals = ?, history = ?, medication = ?, treatment = ? WHERE medno = ?");

            pst.setString(1, pname);
            pst.setString(2, vitals);
            pst.setString(3, history);
            pst.setString(4, med);
            pst.setString(5, tment);
            pst.setString(6, pno);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Info Updated");

            AutoID();
            Tfname.setText("");
            Jvitals.setSelectedItem("DROP TO SELECT");
            Jhistory.setSelectedItem("DROP TO SELECT");
            Jmed.setSelectedItem("DROP TO SELECT");
            Jtment.setSelectedItem("DROP TO SELECT");
            Tfname.requestFocus();
            showmedtbl();
            AddButton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String pname = Tfname.getText();
        String vitals = (String) Jvitals.getSelectedItem();
        String history = (String) Jhistory.getSelectedItem();
        String med = (String) Jmed.getSelectedItem();
        String tment = (String) Jtment.getSelectedItem();
        String pno = idno.getText();

        try {
            pst = conn.prepareStatement("DELETE FROM medical_records WHERE medno = ?");

            pst.setString(1, pno);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Info Deleted");

           AutoID();
            Tfname.setText("");
            Jvitals.setSelectedItem("DROP TO SELECT");
            Jhistory.setSelectedItem("DROP TO SELECT");
            Jmed.setSelectedItem("DROP TO SELECT");
            Jtment.setSelectedItem("DROP TO SELECT");
            Tfname.requestFocus();
            showmedtbl();
            AddButton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(MANAGEPX.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void MedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedTableMouseClicked
        DefaultTableModel dl = (DefaultTableModel)MedTable.getModel();
        int SelectIndex = MedTable.getSelectedRow();

            idno.setText(dl.getValueAt(SelectIndex, 0).toString());
            Tfname.setText(dl.getValueAt(SelectIndex, 1).toString());
            Jvitals.setSelectedItem(dl.getValueAt(SelectIndex, 2).toString());
            Jhistory.setSelectedItem(dl.getValueAt(SelectIndex, 3).toString());
            Jmed.setSelectedItem(dl.getValueAt(SelectIndex, 4).toString());
            Jtment.setSelectedItem(dl.getValueAt(SelectIndex, 5).toString());
            AddButton.setEnabled(false);
            EditButton.setEnabled(true);
    }//GEN-LAST:event_MedTableMouseClicked

    private void TfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfnameActionPerformed

    private void JhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JhistoryActionPerformed

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
         DefaultTableModel dl = (DefaultTableModel)patientTable.getModel();
            int SelectIndex = patientTable.getSelectedRow();

            idno.setText(dl.getValueAt(SelectIndex, 0).toString());
            Tfname.setText(dl.getValueAt(SelectIndex, 1).toString());
            AddButton.setEnabled(true);
            EditButton.setEnabled(false);
    }//GEN-LAST:event_patientTableMouseClicked

    private void MedTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedTableMousePressed

    private void patientTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientTableKeyReleased
       
    }//GEN-LAST:event_patientTableKeyReleased

    private void patientTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseExited
 
    }//GEN-LAST:event_patientTableMouseExited

    private void JvitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JvitalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JvitalsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           conn = Ge.getConnection();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PXDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PXDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PXDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PXDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PXDATA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JComboBox<String> Jhistory;
    private javax.swing.JComboBox<String> Jmed;
    private javax.swing.JComboBox<String> Jtment;
    private javax.swing.JComboBox<String> Jvitals;
    private javax.swing.JTable MedTable;
    private javax.swing.JTextField Tfname;
    private javax.swing.JLabel idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables
}
