/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmhcprms;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.knowm.xchart.BitmapEncoder;

import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;

import org.knowm.xchart.style.Styler;

/**
 *
 * @author Jed
 */
public class TRENDS extends javax.swing.JFrame {

    /**
     * Creates new form TRENDS
     */
    private JPanel chartPanel;
    private JPanel chartPanelDiag;

    private CategoryChart chartForHis;
    private CategoryChart chartForDiag;

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TRENDS() {
        conn = Ge.getConnection();
        initComponents();
        CHART_PANEL_DIAGNOSIS.setVisible(false);
        CHART_PANEL.setVisible(true);
        BUTTON_DIAG.setVisible(false);

        DISPLAYCHART();

//        SORT_DROPDOWN.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent e) {
//                Object selectedBatch = SORT_DROPDOWN.getSelectedItem();
//                if (selectedBatch.equals("Unsorted")) {
//                    DISPLAYCHART();
//                } else {
////                    SORTED();
//                }
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CHART_PANEL_DIAGNOSIS = new javax.swing.JPanel();
        CHART_PANEL = new javax.swing.JPanel();
        BUTTON_HISTORY = new javax.swing.JButton();
        BUTTON_DIAG = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(225, 212, 187));

        jPanel1.setBackground(new java.awt.Color(83, 113, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(225, 212, 187));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Polomolok Mental Health-Care Patient Records & Monitoring System 2023");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 624, 540, 90));

        jPanel2.setBackground(new java.awt.Color(203, 178, 121));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 80));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MANAGE PATIENTS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 154, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appointment.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 80));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("APPOINTMENTS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 154, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 75, 80));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PATIENT DATA");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 154, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/finance-and-business.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 73, 80));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REPORTS");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 100, 160, 50));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 160));

        javax.swing.GroupLayout CHART_PANEL_DIAGNOSISLayout = new javax.swing.GroupLayout(CHART_PANEL_DIAGNOSIS);
        CHART_PANEL_DIAGNOSIS.setLayout(CHART_PANEL_DIAGNOSISLayout);
        CHART_PANEL_DIAGNOSISLayout.setHorizontalGroup(
            CHART_PANEL_DIAGNOSISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        CHART_PANEL_DIAGNOSISLayout.setVerticalGroup(
            CHART_PANEL_DIAGNOSISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel5.add(CHART_PANEL_DIAGNOSIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 180, 820, 420));

        javax.swing.GroupLayout CHART_PANELLayout = new javax.swing.GroupLayout(CHART_PANEL);
        CHART_PANEL.setLayout(CHART_PANELLayout);
        CHART_PANELLayout.setHorizontalGroup(
            CHART_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        CHART_PANELLayout.setVerticalGroup(
            CHART_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel5.add(CHART_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 800, 380));

        BUTTON_HISTORY.setText("EXPORT GRAPH");
        BUTTON_HISTORY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_HISTORYActionPerformed(evt);
            }
        });
        jPanel5.add(BUTTON_HISTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 180, 40));

        BUTTON_DIAG.setText("EXPORT GRAPH");
        BUTTON_DIAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_DIAGActionPerformed(evt);
            }
        });
        jPanel5.add(BUTTON_DIAG, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 180, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 180, -1));

        jButton2.setText("DIAGNOSIS GRAPH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, 180, 40));

        jButton3.setText("PATIENT HISTORY GRAPH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 180, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DASHBOARD s = new DASHBOARD();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MANAGEPX s = new MANAGEPX();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        APPOINTMENTS s = new APPOINTMENTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        PXDATA s = new PXDATA();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        REPORTS s = new REPORTS();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void BUTTON_HISTORYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_HISTORYActionPerformed
        // Print the chart
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new ChartPrintable(chartPanel));
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_BUTTON_HISTORYActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        CHART_PANEL.setVisible(false);
        BUTTON_HISTORY.setVisible(false);

        DISPLAYCHART_FOR_DIAGNOSIS();

        BUTTON_DIAG.setVisible(true);

        CHART_PANEL_DIAGNOSIS.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CHART_PANEL.setVisible(true);
        BUTTON_HISTORY.setVisible(true);

        DISPLAYCHART();

        BUTTON_DIAG.setVisible(false);

        CHART_PANEL_DIAGNOSIS.setVisible(false);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void BUTTON_DIAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_DIAGActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new ChartPrintable(chartPanelDiag));
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_BUTTON_DIAGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRENDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRENDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRENDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRENDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRENDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_DIAG;
    private javax.swing.JButton BUTTON_HISTORY;
    private javax.swing.JPanel CHART_PANEL;
    private javax.swing.JPanel CHART_PANEL_DIAGNOSIS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private void DISPLAYCHART() {
        chartForHis = new CategoryChartBuilder().width(800).height(600).theme(Styler.ChartTheme.Matlab).build();

        chartForHis.setTitle("PATIENT HISTORY GRAPH");
        chartForHis.setXAxisTitle("History");
        chartForHis.setYAxisTitle("Number of Patients");

        try {
            String query = "SELECT history, ROW_NUMBER() OVER (ORDER BY history) AS count "
                    + "FROM medical_records "
                    + "GROUP BY history";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            List<String> xValues = new ArrayList<>();
            List<Integer> yValues = new ArrayList<>();

            int count = 1;

            while (rs.next()) {
                String history = rs.getString("history");

                xValues.add(history);
                yValues.add(count);

                count++;
            }

            Color darkerBeige = new Color(210, 180, 140);
            chartForHis.addSeries("Patient Count", xValues, yValues).setFillColor(darkerBeige);

        } catch (SQLException e) {
            e.printStackTrace();
        }

        chartPanel = new XChartPanel<>(chartForHis);
        CHART_PANEL.setLayout(new BorderLayout());
        CHART_PANEL.add(chartPanel, BorderLayout.CENTER);

        pack();
        setVisible(true);
    }

    private static class ChartPrintable implements Printable {

        private final Component chartComponent;

        public ChartPrintable(Component chartComponent) {
            this.chartComponent = chartComponent;
        }

        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if (pageIndex > 0) {
                return NO_SUCH_PAGE;
            }

            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

            // Scale the chart to fit the printable area
            double scaleX = pageFormat.getImageableWidth() / chartComponent.getWidth();
            double scaleY = pageFormat.getImageableHeight() / chartComponent.getHeight();
            double scale = Math.min(scaleX, scaleY);

            g2d.scale(scale, scale);

            // Paint the chart component onto the printable area
            chartComponent.printAll(graphics);

            return PAGE_EXISTS;
        }
    }

    private void DISPLAYCHART_FOR_DIAGNOSIS() {
        chartForDiag = new CategoryChartBuilder().width(800).height(600).theme(Styler.ChartTheme.Matlab).build();

        chartForDiag.setTitle("DIAGNOSIS GRAPH");
        chartForDiag.setXAxisTitle("Diagnosis");
        chartForDiag.setYAxisTitle("Number of Patients");

        try {
            String query = "SELECT diagnosis, COUNT(*) AS count FROM patient_records GROUP BY diagnosis";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            List<String> xValues = new ArrayList<>();
            List<Integer> yValues = new ArrayList<>();

            while (rs.next()) {
                String diagnosis = rs.getString("diagnosis");
                int count = rs.getInt("count");

                xValues.add(diagnosis);
                yValues.add(count);
            }

            Color darkerBeige = new Color(210, 180, 140);
            chartForDiag.addSeries("Patient Count", xValues, yValues).setFillColor(darkerBeige);

        } catch (SQLException e) {
            e.printStackTrace();
        }

        chartPanelDiag = new XChartPanel<>(chartForDiag);
        CHART_PANEL_DIAGNOSIS.setLayout(new BorderLayout());
        CHART_PANEL_DIAGNOSIS.add(chartPanelDiag, BorderLayout.CENTER);

        pack();
        setVisible(true);
    }

}
